name: deploy

on:
  push:
    tags:
      - 'docs.**'  # e.g. docs.20240101
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build  # 默认输出到 dist，如果是别的目录请替换

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist  # 你的构建输出目录

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

